<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Certificate;
use Illuminate\Support\Facades\Storage;

class CleanupCorruptedCertificates extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'certificates:cleanup-corrupted';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Delete corrupted certificates generated by the old synchronous flow (certificates table)';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting cleanup of corrupted certificates...');

        // We are targeting the 'certificates' table which was used by the broken flow.
        // The new flow uses 'course_certificates'.
        
        $count = Certificate::count();
        
        if ($count === 0) {
            $this->info('No certificates found in the old table.');
            return;
        }

        if (!$this->confirm("Found {$count} certificates in the 'certificates' table. Do you want to delete them? This cannot be undone.")) {
            $this->info('Operation cancelled.');
            return;
        }

        $bar = $this->output->createProgressBar($count);
        $bar->start();

        foreach (Certificate::cursor() as $certificate) {
            // Optional: Delete the file if it exists
            if ($certificate->file_path && Storage::disk('public')->exists($certificate->file_path)) {
                Storage::disk('public')->delete($certificate->file_path);
            }

            $certificate->delete();
            $bar->advance();
        }

        $bar->finish();
        $this->newLine();
        $this->info('Successfully deleted corrupted certificates.');
    }
}
